spring:
  application:
    name: xpensetrack
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/xpensetrack}


jwt:
  secret: ${JWT_SECRET:xpensetrack-secret-key-change-in-production-min-256-bits-long-key}
  expiration: ${JWT_EXPIRATION:604800000}  # 7 days

server:
  port: ${PORT:${SERVER_PORT:8080}}
